### ISSUE TITLE
Add custom dictionary

### ISSUE THREAD

**Issue by fanweihua** [PyThaiNLP/attacut#21]
Is there a way to add custom dictionary? like deepcut?

**Comment by heytitle** [comment]
Hi @fanweihua,

Thanks for your issue!  Unfortunately, we don't have such a feature. Could you please elaborate a bit more about your usecase?

**Comment by fanweihua** [comment]
I've been evaluating deepcut and attacut. I was impressed by attacut's speed. But I need the feature for custom dictionary if  the tokenization result is not what I expect.

**Comment by heytitle** [comment]
this repo might be useful for you in this case; you can use it to post-process the tokenized text.

https://github.com/heytitle/mudyom

Feel free ping me if you have any further question!
