### ISSUE TITLE
Provide a way to make part of text not to be tokenized

### ISSUE THREAD

**Issue by fanweihua** [PyThaiNLP/attacut#25]
I've been using attacut to process Thai chat corpus. The problem is many texts contain hyperlink, emoji, email addr, etc. I detect these entities and try to use placeholders to replace them before sending them to attacut hoping that attacut will leave them untoudhed. The placeholders I use are long english word string like "EMOJIPLACEHOLDER". It works for other tokenizers like deepcut, but attacut occasionly cut the placeholder into pieces: "EMO JIPLACEHOLDER".

So is there any way that I can tell attacut not to cut a string in a line of text?
Or any way to work around this problem?

Thanks.

**Comment by heytitle** [comment]
Hi @fanweihua, thanks for getting in touch.

When developing AttaCut, I didn't realize such a case; however, it seems to be very important in practice. I'll take a look and see how people solve it.

For the work around, one way that I can think of is to do post processing. Consider the result from AttaCut:

```
this|is|bad|EMO|JIPLACEHOLDER
```

Briefly, you define those wrong segmentations in `dict.txt`:

```
EMOJIPLACEHOLDER
``` 

and use https://github.com/heytitle/mudyom#example to combine `EMO` and `JIPLACEHOLDER` together.

**Comment by heytitle** [comment]
I'll close this issue; feel free to reopen it if you still have an issue.
