### ISSUE TITLE
the accuracy between "AttaCut" and "newmm".

### ISSUE THREAD

**Issue by charlesfufu** [PyThaiNLP/attacut#26]
Why the accuracy of "AttaCut" model more worse than "newmm"  throgh PyThaiNLP in TNHC(Thai National Historical Corpus) dataset?
Is there any problem that needs my attention？
<img width="816" alt="屏幕快照 2020-12-31 下午5 36 01" src="https://user-images.githubusercontent.com/33311822/103404485-b475f280-4b8e-11eb-8072-3e7facc10ba6.png">
And, do you what's the meaning of "<s>、#、$" in TNHC dataset？

**Comment by heytitle** [comment]
Regarding the first question, we have some discussion in https://arxiv.org/pdf/1911.07056.pdf, Section 5.4. I'll post the snapshot here:

![image](https://user-images.githubusercontent.com/1214890/103414928-41fe1600-4b80-11eb-8fc4-d0ba1b303c8f.png)


> And, do you what's the meaning of "、#、$" in TNHC dataset？
I don't know either.

**Comment by charlesfufu** [comment]
> https://arxiv.org/pdf/1911.07056.pdf

Thanks for your reply. 
 So, can you provide some BEST dataset(tokenized data) for evaluating ?

**Comment by charlesfufu** [comment]
> Regarding the first question, we have some discussion in https://arxiv.org/pdf/1911.07056.pdf, Section 5.4. I'll post the snapshot here:
> 
> ![image](https://user-images.githubusercontent.com/1214890/103414928-41fe1600-4b80-11eb-8fc4-d0ba1b303c8f.png)
> 
> > And, do you what's the meaning of "、#、$" in TNHC dataset？
> > I don't know either.
