### ISSUE TITLE
Uplift version pin of nptying

### ISSUE THREAD

**Issue by BLKSerene** [PyThaiNLP/attacut#28]
I'm wondering that if there is any reason that the `nptying` dependency is pinned at `<=0.3.1` while the latest version of `nptying` is `1.4.0`?

**Comment by wannaphong** [comment]
`attacut/evaluation.py` couldn't working with nptyping>= 1.0. Now, `nptyping` not has `nptyping.Array`   https://github.com/PyThaiNLP/attacut/blob/master/attacut/evaluation.py#L5

**Comment by BLKSerene** [comment]
Thanks for the clarification.

**Comment by BLKSerene** [comment]
`nptyping.Array` was deprecated in `nptyping` 1.0.0, is it possible to use `nptyping.NDArray` instead?

**Comment by heytitle** [comment]
I think we should move to `nptyping.NDArray`; however, I won't have time to update it. Would you mind sending us a PR?
