### ISSUE TITLE
What is the format of the input data？

### ISSUE THREAD

**Issue by so-coolboy** [PyThaiNLP/attacut#29]
I want to continue training attacut on my own data set, but I am not sure what the format of the data set should be?
![截图](https://user-images.githubusercontent.com/22762396/119309676-3206e000-bca1-11eb-8e11-6e468d23256f.png)
The data set link here is no longer valid, so I cannot view the format of the data set, can you help me?

**Comment by heytitle** [comment]
@so-coolboy perhaps, this issue might be of your interest https://github.com/PyThaiNLP/attacut/issues/20.

**Comment by so-coolboy** [comment]
thank you, 😊
