### ISSUE TITLE
Datasets cannot be accessed

### ISSUE THREAD

**Issue by tchayintr** [PyThaiNLP/attacut#31]
The datasets on https://pythainlp.github.io/attacut/training.html could not be accessed.
In additional, without taking a look at the datasets, the example in https://pythainlp.github.io/attacut/training.html#how-to-retrain-on-custom-dataset is not clear enough to follow (in my opinion).

**Comment by heytitle** [comment]
@tchayintr thank you for your interest in our work!

I apologize that the document is outdated.  Perhaps, you can check this closed issue: https://github.com/PyThaiNLP/attacut/issues/20.

Alternatively, you might also check the published version of AttaCut at https://github.com/heytitle/Syllable-based-Neural-Thai-Word-Segmentation.
