### ISSUE TITLE
custom_dict param is not working properly on attacut tokenizer

### ISSUE THREAD

**Issue by sahussawud** [PyThaiNLP/attacut#35]
**Env:** 
 - Google Colab 

**Version :** 
- pythainlp (3.0.5)
- attacut (1.0.6)

as Docs [pythainlp.tokenize.word_tokenize](https://pythainlp.github.io/docs/3.0/api/tokenize.html#pythainlp.tokenize.word_tokenize) said Attacut tokenizer provided custom_dict param. However, it seem not working properly.

```
from pythainlp.corpus.common import thai_words
from pythainlp.util import dict_trie
from pythainlp.tokenize import Tokenizer

custom_words_list = set(thai_words())
custom_words_list |= set(['ต้องการระบาย'])
trie = dict_trie(dict_source=custom_words_list)

_tokenizer = Tokenizer(custom_dict=trie, engine='attacut')

_tokenizer.word_tokenize('ต้องการ')
```
output

`['ต้องการ', 'ระบาย']`

expected output

`['ต้องการระบาย']`

PS1. I also tested with pythainlp.tokenize.word_tokenize. it's worked similar to above. 
PS2. newmm and longest engine still work with custom_dict param.

**Comment by wannaphong** [comment]
Sorry, the docs is wrong because attacut tokenizer doesn't support custom_dict. We apologize for this mistake.
