### ISSUE TITLE
UnicodeDecodeError Problem

### ISSUE THREAD

**Issue by pitiphol** [PyThaiNLP/attacut#7]
using tokenize function caused UnicodeDecodeError from load_dict function in utils.py

**Comment by bact** [comment]
Should be fixed by this commit: https://github.com/PyThaiNLP/attacut/commit/c8669828c94ac7059dd56fb75e216755667e139b

**Comment by heytitle** [comment]
@pitiphol I've just published AttaCut with @bact 's fix.

Would you mind testing it?
https://pypi.org/project/attacut/1.0.2.dev0/

Feel free to reopen the issue if there is still the problem
